title: ButtonBoxLib Docs
description: Documentation for the ButtonBoxLib library.
theme: just-the-docs

url: https://roboblazers7617.github.io/ButtonBoxLib
javadoc_url: https://roboblazers7617.github.io/ButtonBoxLib/javadoc

aux_links:
  Repository: https://github.com/roboblazers7617/ButtonBoxLib

nav_external_links:
  - title: Java API documentation
    url: https://roboblazers7617.github.io/ButtonBoxLib/javadoc
